### ISSUE TITLE
The time for react-native come ?

### ISSUE THREAD

**Issue by LeezQ** [react-team/React-Native#1]
can't wait anymore :laughing:

**Comment by cmnstmntmn** [comment]
yeah > when ?

**Comment by taneltm** [comment]
http://devchat.tv/js-jabber/146-jsj-react-with-christopher-chedeau-and-jordan-walke
15:38 - "In a few months, when we think we are ready, we are going to open it for everybody"
Podcast published: 02/11/15

**Comment by LeezQ** [comment]
few months is so long .... 😢

**Comment by AndyChenW** [comment]
few months...
